### PR TITLE
Feature/add ctr prng

### PR DESCRIPTION
**Pull request by chris-morrison**
Hi,

This branch adds CTR PRNG functionality, which uses the AES primitives.

Useful for applications that are already using AES and need a PRNG (without having to pull in the HMAC/SHA functionality).

I've tried to keep naming/styles/conventions consistent with the existing codebase.

Thanks,
Chris

### CODE REVIEW

**Comment by ware** [comment]
I'm sure @hackermnementh will take a look at this early this coming week.  I'm happy to see someone contributing code!  :-)

**Comment by hackermnementh** [comment]
Thanks! I was OOO Friday but will get this in Monday.

On Feb 19, 2016, at 8:43 PM, chris-morrison <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

This branch adds CTR PRNG functionality, which uses the AES primitives.

Useful for applications that are already using AES and need a PRNG (without having to pull in the HMAC/SHA functionality).

I've tried to keep naming/styles/conventions consistent with the existing codebase.

Thanks,
Chris

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/01org/tinycrypt/pull/3

Commit Summary

  *   initial commit of ctr_prng
  *   fixing key setup during ctr_prng_init
  *   Adding support for additional input when reseeding/generating ctr prngs. Also added documentation
  *   fixing usage of additional input when generating ctr prng output
  *   adding test vectors for ctr prng
  *   updating documentation to cover CTR-PRNG

File Changes

  *   A .gitignore<https://github.com/01org/tinycrypt/pull/3/files#diff-0> (2)
  *   M VERSION<https://github.com/01org/tinycrypt/pull/3/files#diff-1> (2)
  *   M documentation/tinycrypt.rst<https://github.com/01org/tinycrypt/pull/3/files#diff-2> (17)
  *   M lib/Makefile<https://github.com/01org/tinycrypt/pull/3/files#diff-3> (2)
  *   A lib/include/tinycrypt/ctr_prng.h<https://github.com/01org/tinycrypt/pull/3/files#diff-4> (165)
  *   A lib/source/ctr_prng.c<https://github.com/01org/tinycrypt/pull/3/files#diff-5> (307)
  *   M tests/Makefile<https://github.com/01org/tinycrypt/pull/3/files#diff-6> (6)
  *   A tests/test_ctr_prng.c<https://github.com/01org/tinycrypt/pull/3/files#diff-7> (545)

Patch Links:

  *   https://github.com/01org/tinycrypt/pull/3.patch
  *   https://github.com/01org/tinycrypt/pull/3.diff

�

**Comment by chris-morrison** [comment]
Hi @hackermnementh,

Any feedback on this branch - happy to take on board on any comments/suggestions you may have.

Best regards,
Chris

**Comment by hackermnementh** [comment]
Hi Chris-
     Sorry I’ve been out of office, I was waiting for some feedback from some other crypto experts before merging. I’ll try to pull it in this week if they have no further feedback. Really appreciate this and had I not been traveling would be in already.

Constanza M. Heath
Security Researcher
SSG OTC Security Team

**Comment by chris-morrison** [comment]
No worries - please take whatever time is needed. Much better to get it
right than to rush!

Cheers,
Chris

**Pull request merged**
